### PR TITLE
changed get_item to return a reference to the original value

### PR DESCRIPTION
**Pull request by ofloveandhate**
instead of a copy

### CODE REVIEW

**Comment by eudoxos** [comment]
Looks good for me, internal reference should tie lifetime of the reference to the containing object.

**Comment by eudoxos** [comment]
Is is possible that this triggered #18?

**Comment by ofloveandhate** [comment]
sorry this didn't work out, and that you had to revert.  *hangs head*

i still think that returning internal reference is the thing to do, as otherwise multiprecision objects are returned as copies, which is both slow and wrong.

**Comment by eudoxos** [comment]
It is the best conceptually, I am a bit surprised the code could not compile, but if you manage to solve that, I am all for that change.

**Comment by ofloveandhate** [comment]
did you grok at all why it failed to compile?

**Pull request merged**
